# Generated by Django 2.1.3 on 2018-11-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='last_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25),
        ),
    ]
